/*Queries that provide answers to the questions from all projects.*/

SELECT * from animals WHERE name = 'Luna';


CREATE TABLE invoice_items (
    id int NOT NULL GENERATED BY DEFAULT as IDENTITY(start with 1) PRIMARY KEY,
    unit_price decimal,
    quantity int,
    total_price decimal,
    invoice_id int REFERENCES invoices(id),
    treatment_id int REFERENCES treatments(id)
);