/* Database schema to keep the structure of entire database. */

CREATE TABLE patients (
    id int NOT NULL GENERATED BY DEFAULT as IDENTITY(start with 1) PRIMARY KEY,
    name varchar(50),
    date_of_birth date
);

CREATE TABLE medical_histories (
    id int NOT NULL GENERATED BY DEFAULT as identity(start with 1) PRIMARY KEY,
    admited_at timestamp,
    patient_id int REFERENCES patients(id),
    status varchar(100)
);

CREATE TABLE treatments (
    id int NOT NULL GENERATED BY DEFAULT as IDENTITY(start with 1) PRIMARY KEY,
    type varchar(50),
    name varchar(50)
);

CREATE TABLE medical_histories_treatments (
    id int NOT NULL GENERATED BY DEFAULT as IDENTITY(start with 1) PRIMARY KEY,
    medical_history_id int NOT NULL REFERENCES medical_histories(id),
    treatment_id int NOT NULL REFERENCES treatments(id)
);

CREATE TABLE invoices (
    id int NOT NULL GENERATED BY DEFAULT as IDENTITY(start with 1) PRIMARY KEY,
    total_amount decimal,
    generated_at timestamp,
    payed_at timestamp,
    medical_history_id int REFERENCES medical_histories(id)
);


